version: "3"

services:
  battleship:
    container_name: battleship
    build: .
    restart: always
    image: battleship:1.0.0
    ports:
      - 3000:3000
    env_file:
      - .env
    environment:
      - MONGO_CONNECTION_URL=mongodb://mongo:27017/battleship
    depends_on:
      - mongo
  mongo:
    image: mongo:latest
    restart: always
    environment:
      - MONGODB_DATABASE="battleship"
    ports:
      - 27017:27017

   
      
